In [1]:
import pandas as pd
import numpy as np
import os
from pandas import DataFrame
from sekwencyjnosc_koncentracji import s_kon

In [7]:
data = pd.read_csv('d2-R_data.csv',delimiter='\t')
data

    ID  wiek  P  LPZW    K   B%  k1  k2  k3  k4
0  P07    21  1   120  115  108  47  63  65  58
1  P07    21  2   132  135  116  67  72  67  68
2  P21    48  1   121  124  102  47  53  51  52
3  P21    48  2   117  122  105  48  55  48  45
4  P22    47  1    98   91   87  21  28  33  35
5  P22    47  2    90   95  101  31  31  33  30

In [21]:
rows = []

for _, row in data.iterrows():
    b1,b2,b3,b4 = s_kon(row['wiek'], row['k1'], row['k2'], row['k3'], row['k4'])
    rows.append({'ID': row['ID'], 'P': row['P'],
                 'blok1': b1, 'blok2': b2, 'blok3': b3, 'blok4': b4})

sKon_results = pd.DataFrame(rows)
sKon_results

    ID  P  blok1  blok2  blok3  blok4
0  P07  1 -16.89   4.79   9.49   2.22
1  P07  2  -3.89   3.19  -1.22   1.88
2  P21  1  -5.60   2.59   0.49   2.98
3  P21  2  -1.68   8.23  -1.44  -5.29
4  P22  1 -12.02  -2.68   5.90  10.07
5  P22  2  -0.61  -1.17   2.81  -0.96